### ISSUE TITLE
MMM decoder

### ISSUE THREAD

**Issue by wzr1013** [microsoft/PhysioPro#19]
In the code related to the MMM paper that I have examined, it seems that there is no provision for pre-trained models and their corresponding code. The MMM.py section only includes fine-tuning, and does not involve the decoder component either.
 I'm not sure if I missed where to find it, or if I need to create it myself.

**Comment by victorywys** [comment]
Hi, thanks for your interest in our paper! Currently we don't have the plan to open-source our codes for the pretraining stage. Instead, we provide the pretrained checkpoint [here](https://seqml.github.io/MMM/). You can load the pretrained weights for down-stream task fine-tuning with our codes, which incorporate the feature of the core contributions in the paper, i.e., the multi-dimensional positional encoding and the multi-level channel hierarchy.
